TIER1_HIGH_PRICE = ['MEBL', 'OGDC', 'FFC', 'LUCK', 'MARI', 'HUBC', 'ABOT', 'NESTLE', 'ATLH', 'UBL']
TIER2_MID_PRICE  = ['FABL', 'EFERT', 'FCCL', 'NML', 'SNGP', 'SYS', 'AGP', 'ISL', 'AICL', 'TGL']
TIER3_LOW_PRICE  = ['AHCL', 'CNERGY', 'HUMNL', 'KAPCO', 'KEL', 'LOTCHEM', 'PIBTL', 'POWER', 'SSGC', 'YOUW']

UNIVERSE = TIER1_HIGH_PRICE + TIER2_MID_PRICE + TIER3_LOW_PRICE
assert len(UNIVERSE) == 30